<?php

/** Implements hook_formID_alter
 *
 * Adds settings for Open Platform client
 *
 * @see ting_client_admin_webservices_settings
 * in ting_client.admin.inc
 *
 * @param $form
 * @param $form_state
 */
function open_platform_form_ting_client_admin_webservices_settings_alter(&$form, &$form_state) {
  $form['openPlatform'] = array(
    '#type' => 'fieldset',
    '#title' => 'Open Platform settings',
    '#description' => t('The Open Platform service is an abstraction layer for DBC webservices.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
    '#tree' => FALSE,
  );
  $form['openPlatform']['openplatform_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Open Platform URL'),
    '#description' => t('URL to openPlatform webservice'),
    '#required' => TRUE,
    '#default_value' => variable_get('openplatform_url', ''),
  );
  $form['openPlatform']['openplatform_recommender_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Open Platform recommender URL'),
    '#description' => t('URL to openPlatform recommender'),
    '#required' => TRUE,
    '#default_value' => variable_get('openplatform_recommender_url', ''),
  );
  $form['openPlatform']['openplatform_token_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Open Platform token URL'),
    '#description' => t('URL to openPlatform tokens'),
    '#required' => TRUE,
    '#default_value' => variable_get('openplatform_token_url', ''),
  );
  $form['openPlatform']['openplatform_client_id'] = array(
    '#type' => 'textfield',
    '#title' => t('Open Platform client ID'),
    '#required' => TRUE,
    '#default_value' => variable_get('openplatform_client_id', ''),
  );
  $form['openPlatform']['openplatform_client_secret'] = array(
    '#type' => 'textfield',
    '#title' => t('Open Platform client secret'),
    '#required' => TRUE,
    '#default_value' => variable_get('openplatform_client_secret', ''),
  );
}


/**
 * Implements hook_ting_client_webservice (@see ting_client.module)
 * */
function open_platform_ting_client_webservice() {
  $ret = array();
  $ret['openPlatform']['class'] = 'OpenPlatformRequest';
  $ret['openPlatform']['url'] = 'openplatform_url';
  $ret['openPlatformRecommender']['class'] = 'RecommenderRequest';
  $ret['openPlatformRecommender']['url'] = 'openplatform_recommender_url';
  $ret['openPlatformToken']['class'] = 'OpenPlatformTokenRequest';
  $ret['openPlatformToken']['url'] = 'openplatform_token_url';
  return $ret;
}


/** Generic request function to call Open Platform
 * @param $method
 * @param $params
 * @return json
 */
function open_platform_request($method, $params) {
  
  $request = 'openPlatform' . ucfirst($method);
  
  $params['action'] = $method . 'Request';
  $params['requestParameters']['access_token'] = variable_get('open_platform_access_token', NULL);
  $params['curlOptions'] = array(
    CURLOPT_POST => TRUE,
    CURLOPT_POSTFIELDS => json_encode($params['requestParameters']),
    CURLOPT_HTTPHEADER => array(
      'Content-type: application/json',
      'Accept: application/json'
    )
  );
  
  try {
    $client = new ting_client_class();
    $response = $client->do_request($request, $params);
    open_platform_parse_response($method, $response);
	}
	catch (Exception $e) {
    watchdog('open_platform_authenticate', $e->getMessage(), array(), WATCHDOG_CRITICAL, NULL);
	}
  
  return $response;
}


/** Generic parse function for Open Platform response.
 * @param $method
 * @response $params
 * @return json
 */
function open_platform_parse_response($method = NULL, &$response = NULL) {
  if (!$response) {
    return array();
  }
  $response = json_decode($response);
  if (!$response) {
    throw new Exception("Can't decode response as JSON: " . print_r($response, 1));
  }
  switch ($method) {
    case 'recommender' :
      $response = (!empty($response->data)) ? $response->data : array();
      break;
    case 'authenticate' :
      $response = (!empty($response->access_token)) ? $response->access_token : NULL;
      if (!$response) {
        throw new Exception("Empty Open Platform access token: " . print_r($response, 1));
      }
      break;
    default :
      break;
  }
}

/**
 * Execute Open Platform recommender request
 * @param array $pids
 * @param int $limit
 * @return array
 */
function open_platform_recommender_request($pids, $limit = 10) {
  $method = 'recommender';
  /* full parameters example
  $params['requestParameters'] = array(
    'fields' => array ('string'), // returned fields, ie. array('pid','val','from')
    'pretty' => true,
    'timings' => true,
    'like' => $pids,
    'ignore' => array ('870970-basis:12345678'),
    'limit' => $limit,
    'offset' => 0,
    'filters' => (object) array(
      'authorFlood' => 0,
      'subject' => array('string'),
      'type' => array('string'),
      'language' => array('string'),
      'newerThan' => 0,
      'olderThan' => 0,
    ),
    'boosters' => (object) array(
      'loanCount' => 0,
    )
  );
  */
  // simplified parameters
  $params['requestParameters'] = array(
    'like' => $pids,
    'limit' => $limit,
    'offset' => 0,
  );
  return open_platform_request($method, $params);
}


/** Open Platform authenticate
 *
 * @return string
 */
function open_platform_authenticate_request() {
  $params['action'] = 'authenticateRequest';
  $params['requestParameters'] = array(
    'grant_type' => 'password',
    'username' => '@',
    'password' => '@',
  );
  $params['curlOptions'] = array(
    CURLOPT_POST => TRUE,
    CURLOPT_USERNAME => variable_get('openplatform_client_id', NULL),
    CURLOPT_PASSWORD => variable_get('openplatform_client_secret', NULL),
    CURLOPT_POSTFIELDS => http_build_query($params['requestParameters']),
    CURLOPT_HTTPHEADER => array(
      'Content-type: application/x-www-form-urlencoded',
      'Accept: application/json'
    ),
  );
  try {
    $client = new ting_client_class();
    $response = $client->do_request('openPlatformToken', $params);
    open_platform_parse_response('authenticate', $response);
	}
	catch (Exception $e) {
    watchdog('open_platform_authenticate', $e->getMessage(), array(), WATCHDOG_CRITICAL, NULL);
	}
  variable_set('open_platform_access_token', $response);
  return $response;
}

/**
 * Implements hook_cron
 *
 * Get/update access token for Open Platform.
 * Token expires in a month, so if we renew it with cron, it should never be expired.
 */
function open_platform_cron() {
  open_platform_authenticate_request();
}

